
export const SET_LOADING = 'SET_LOADING';
export const SET_AREA_LIST = 'SET_AREA_LIST';
export const SET_POST_CATEGORIES = 'SET_POST_CATEGORIES';
export const SET_GROUP_CATEGORIES = 'SET_GROUP_CATEGORIES';

//--- User data ---
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AVATAR = 'SET_AVATAR';
export const SET_MYPOSTS = 'SET_MYPOSTS';
export const SET_MYGROUPS = 'SET_MYGROUPS';
export const SET_SUPPORT_GROUPS = 'SET_SUPPORT_GROUPS';
export const DELETE_USER_POST = 'DELETE_USER_POST';
export const DELETE_USER_GROUP = 'DELETE_USER_GROUP';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

//--- Home ---
export const SET_LATEST_GROUP_LIST = 'SET_LATEST_GROUP_LIST';
export const SET_LATEST_POST_LIST = 'SET_LATEST_POST_LIST';

//--- Post Search ---
export const SET_POST_SEARCH_RESULT = 'SET_POST_SEARCH_RESULT';
export const SET_POST_SEARCH_AREA = 'SET_POST_SEARCH_AREA';
export const SET_POST_SEARCH_CATEGORIES = 'SET_POST_SEARCH_CATEGORIES';

//--- Group Search ---
export const SET_GROUP_SEARCH_RESULT = 'SET_GROUP_SEARCH_RESULT';
export const SET_GROUP_SEARCH_AREA = 'SET_GROUP_SEARCH_AREA';
export const SET_GROUP_SEARCH_CATEGORIES = 'SET_GROUP_SEARCH_CATEGORIES';

//--- Group Details ---
export const SET_GROUP_DETAILS = 'SET_GROUP_DETAILS';
export const SET_GROUP_MEMBERS = 'SET_GROUP_MEMBERS';
export const SET_GROUP_FOLLOWERS = 'SET_GROUP_FOLLOWERS';
export const SET_GROUP_POSTS = 'SET_GROUP_POSTS';
export const CLEAR_GROUP_DETAILS = 'CLEAR_GROUP_DETAILS';

//--- Manage Group ---
export const SET_MANAGE_GROUP_DETAILS = 'SET_MANAGE_GROUP_DETAILS';
export const SET_MANAGE_GROUP_SUPPORT_MEMBERS = 'SET_MANAGE_GROUP_SUPPORT_MEMBERS';
export const SET_MANAGE_GROUP_INVITATIONS = 'SET_MANAGE_GROUP_INVITATIONS';
export const SET_MANAGE_GROUP_FOLLOWERS = 'SET_MANAGE_GROUP_FOLLOWERS';
export const SET_MANAGE_GROUP_POSTS = 'SET_MANAGE_GROUP_POSTS';
export const SET_MANAGE_GROUP_HAS_ERRORS = 'SET_MANAGE_GROUP_HAS_ERRORS';
export const CLEAR_MANAGE_GROUP = 'CLEAR_MANAGE_GROUP';


//--- Comment ---
export const SET_COMMENT_LOADING = 'SET_COMMENT_LOADING';
export const SET_COMMENT_LIST = 'SET_COMMENT_LIST';
export const CLEAR_COMMENT_LIST = 'CLEAR_COMMENT_LIST';
export const LOAD_MORE_COMMENT = 'LOAD_MORE_COMMENT';

//--- Form Errors ---
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';